from decimal import Decimal

from django.conf import settings
from django.db import migrations
from django.db import models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0'),
                        max_digits=14,
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'name',
                    models.CharField(max_length=32),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True)),
                (
                    'name',
                    models.CharField(max_length=32)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.account',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'limit',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.01'))],
                    ),
                ),
                (
                    'period_in_months',
                    models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True)),
                (
                    'name',
                    models.CharField(max_length=32),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.account',
                    ),
                ),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.activity',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY')],
                        default='CZK',
                        max_length=3,
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.activity',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.activity',
                    ),
                ),
                (
                    'budget',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='budgets.budget',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='budgets.profile',
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='budgets.profile',
            ),
        ),
    ]
